version: '3'

services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  
  api:
    image: easymirror-platform-api:latest
    ports:
      - "8080:8080"
    env_file:
      - backend.env
  